### ISSUE TITLE
Bug à la modification d'un produit

### ISSUE THREAD

**Issue by PaulThythy** [Noa-Barbosa/Projet-Genie-Logiciel#30]
Dans la VueModifProduit, on ne peut pas cloner de produits car c'est une interface, et comme this.mProduit est un pointeur vers le produit précédemment sélectionné dans VuePanier, si on le modifie, ça modifie aussi son clone, ce qui pose problème.

Le problème est situé dans l'évènement au clique du bouton valider

**Comment by Noa-Barbosa** [comment]
Problème réglé, j'ai créer des instances de fruit suivant le type de produit modifié
